### PR TITLE
Officer Updates

### PR DESCRIPTION
**Pull request by cforcomputer**
Updates for the first round of officers per Hannah's request. 

> Remove:
Saam Amiri
Hyuen Belle Kim
Annie Kehn
Micheal Vaschillo
Xinyu Wang
Bradt Pascoe
 
> Keep:
Michele Chao - Web Developer
Keep Prathyusha Pillari - Officer
 
> Update:
Phuc Huynh - Vice Chair
Lizzy Presland - Chief Technology Officer
Hannah Sokol - President
Delaney Desmond - Officer

Other changes:

- Updated the packages.json to latest versions
- Deleted old profile photos
- Updated form CSS

image

### CODE REVIEW

**Comment by cforcomputer** [comment]
I wasn't sure how to get the inline errors to display properly. 

They should look like the old form did:
image

Billy wanted form fixed for chrome. I fixed the sizing issues but to really correct the issue, we need to fix the `required` alerts to be attached to their respective boxes.

**Comment by bpas247** [comment]
> I fixed the sizing issues but to really correct the issue, we need to fix the required alerts to be attached to their respective boxes.

https://github.com/UWB-ACM/uwbacm-site/blob/d536495b3ffe9181686aeddc358f4b5761673b5c/src/pages/home/Form.jsx#L97-L102

well the current implementation just directly outputs an array of JSX elements that wrap anything present in the injected `errors` prop. This was more of a hack implementation to begin with, so we should change the implementation so that we just assign an array of JSX elements to a variable, and then render the appropriate JSX element under each appropriate `input` element.

For example...
```jsx
{({handleSubmit, errors}) => {
  const decoratedErrors = errors && {...errors};
  Object.keys(decoratedErrors).forEach(key => {
    decoratedErrors[key] = <div key={key} className="response">{val}</div>;
  });
  return (
  ///....
    <div className="mc-field-group">
       <label htmlFor="mce-EMAIL">
	  Email
	  <span className="asterisk">*</span>
	</label>
	<Field type="email" name="EMAIL" className="required email" id="mce-EMAIL" placeholder="Email" />
        {errors && decoratedErrors["EMAIL"]}
    </div>
  )
}
```

**Comment by cforcomputer** [comment]
> 
> 
> > I fixed the sizing issues but to really correct the issue, we need to fix the required alerts to be attached to their respective boxes.
> 
> https://github.com/UWB-ACM/uwbacm-site/blob/d536495b3ffe9181686aeddc358f4b5761673b5c/src/pages/home/Form.jsx#L97-L102
> 
> well the current implementation just directly outputs an array of JSX elements that wrap anything present in the injected `errors` prop. This was more of a hack implementation to begin with, so we should change the implementation so that we just assign an array of JSX elements to a variable, and then render the appropriate JSX element under each appropriate `input` element.
> 
> For example...
> 
> ```js-jsx
> {({handleSubmit, errors}) => {
>   const decoratedErrors = errors && {...errors};
>   Object.keys(decoratedErrors).forEach(key => {
>     decoratedErrors[key] = <div key={key} className="response">{val}</div>;
>   });
>   return (
>   ///....
>     <div className="mc-field-group">
>        <label htmlFor="mce-EMAIL">
> 	  Email
> 	  <span className="asterisk">*</span>
> 	</label>
> 	<Field type="email" name="EMAIL" className="required email" id="mce-EMAIL" placeholder="Email" />
>         {errors && decoratedErrors["EMAIL"]}
>     </div>
>   )
> }
> ```

While `val` is undefined one line 101, what value should be assigned to `val`?

**Comment by bpas247** [comment]
> While val is undefined one line 101, what value should be assigned to val?

That was mostly example code :) but technically it should be corrected to:
```jsx
  Object.keys(decoratedErrors).forEach(key => {
    decoratedErrors[key] = <div key={key} className="response">{decoratedErrors[key]}</div>;
  });
```

**Comment by cforcomputer** [comment]
Ah, I see 🤔 
I definitely know what I'm doing.
Thank you

**Comment by bpas247** [comment]
Don't worry, I definitely know what I'm doing too 👀

**Comment by bpas247** [comment]
@cforcomputer should be fixed now 😎

**Comment by cforcomputer** [comment]
Aw yeeas, great work

**Comment by cforcomputer** [comment]
Now to figure out how to make it so the `Required` error displays for only fields that have been selected and left empty.

Currently just selecting a box will display all the errors for each field at once, even if the user has not yet selected those fields.

**Pull request merged**
